# Generated by Django 4.1.7 on 2023-03-10 14:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='category')),
                ('title', models.CharField(max_length=255)),
                ('publish', models.DateTimeField(default=datetime.datetime(2023, 3, 10, 14, 55, 8, 172312, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='post')),
                ('model_post', models.CharField(max_length=300)),
                ('cpu', models.CharField(max_length=300)),
                ('ram', models.CharField(max_length=300)),
                ('hard', models.CharField(max_length=300)),
                ('gpu', models.CharField(default='...', max_length=300)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('update', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
    ]
