# Generated by Django 4.1.7 on 2023-03-10 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
